version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      KC_HTTP_RELATIVE_PATH: "/auth"
    command:
      - start-dev
    volumes:
      - ./deployments:/opt/keycloak/providers
